### ISSUE TITLE
Add: https://aws.amazon.com/blogs/aws/new-block-public-sharing-of-amazon-ebs-snapshots/

### ISSUE THREAD

**Issue by Andrey9kin** [fivexl/terraform-aws-account-baseline#2]
If not available theb submit issue to terraform provider and link it here so we can track it

**Comment by EreminAnton** [comment]
For now resource are not created, and issue already exist:
https://github.com/hashicorp/terraform-provider-aws/issues/34347

**Comment by Andrey9kin** [comment]
on SCP level prevent we should block changes to this setting
